### ISSUE TITLE
ParticlePopulation's nonextendability

### ISSUE THREAD

**Issue by jewellsean** [alexandrebouchard/bayonet#31]
I am wondering if there is a good reason (that is not yet apparent to me) why ```ParticlePopulation<P>``` is a final class? I would like to extend this class in order to override the ```logNormEstimate``` method for SMC variants (and add some additional fields, too), but this restraint obviously makes it impossible without rewriting the whole class. 

Thanks!

**Comment by alexandrebouchard** [comment]
The main reason is that final classes are easier to reason about. In 99% of the cases, extending a class A is a sub-optimal strategy. It is usually better to create a new class B that contains an instance of A as a field (this is called composition). This sometimes require creating an interface C for A and B, but not always. Let me know if it does in this case.

Of course, there are some rare cases where that doesn't work, and feel free to remove final then. That will not break current behavior.

Best,
Alex

**Comment by jewellsean** [comment]
Thanks!
