### ISSUE TITLE
Make Bayonet an Eclipse plugin

### ISSUE THREAD

**Issue by cubranic** [alexandrebouchard/bayonet#32]
Using Bayonet from the DSL plugin doesn't work in the slave Eclipse app because the only things on its class path are what's exported through plugin dependencies: [Eclipse FAQ](http://wiki.eclipse.org/Eclipse_Plug-in_Development_FAQ#I.27m_using_third_party_jar_files_and_my_plug-in_is_not_working)

Adding this might be just a matter of click-through wizard magic if everything works: [Eclipse help](http://help.eclipse.org/mars/index.jsp?topic=%2Forg.eclipse.pde.doc.user%2Fguide%2Ftools%2Fpde_actions%2Fconvert_projects.htm)

**Comment by alexandrebouchard** [comment]
Sounds good, feel free to make the change on the bayonet repo in branch blang3-dev

**Comment by cubranic** [comment]
Converting to plugin using the wizard is successful, but:

- the generated build.properties and MANIFEST.MF reference dependency JARs from Gradle cache
- in the slave Eclipse, the .java file generated from the .bl model has syntax errors because Bayonet's packages are not on *its* project's classpath. I'd think this should be possible since it's used in the Build example of the "seven DSLs" tutorial. ([org.xtext.builddsl](https://github.com/xtext/seven-languages-xtext/tree/master/languages/org.xtext.builddsl) uses the runtime provided by [org.xtext.builddsl.lib](https://github.com/xtext/seven-languages-xtext/tree/master/languages/org.xtext.builddsl.lib).

The first problem is discussed [here](https://discuss.gradle.org/t/eclipse-classpath-contains-all-gradle-dependencies-as-libraries/2414), but I'm not clear from the conversation if it was actually solved.

**Comment by cubranic** [comment]
Aha: there is now a plugin for Gradle integration with Eclipse, called [buildship](http://projects.eclipse.org/projects/tools.buildship). This comes with a few plugins, one of which is [BundlePlugin](https://github.com/eclipse/buildship/blob/master/docs/pluginbuild/Usage.md#bundleplugin), and which supposedly "knows how to build Eclipse plugins". Hmm, or maybe this is for being able to run `gradle build` on plugins?

**Comment by alexandrebouchard** [comment]
If this issue is still open, unless this is almost done fixing, I would suggest de-prioritize for later (if the work-around of adding the dependency in the child eclipse manually works). I am proposing this because it occurred to me that somewhere down the road we will probably have to look at ways to help the user create template blang projects, and importing the bayonet jar could be done perhaps more naturally when the template blang project is created.

**Comment by cubranic** [comment]
I agree. I’ll focus on verifying my code through unit tests (both in Eclipse and via gradle would be nice, so we can do CI down the road. It’s way more satisfying to see that green bar in the JUnit view, too. :-)

**Comment by alexandrebouchard** [comment]
Great! Also just to make sure I understand the issue correctly: I am assuming the work-around of adding the bayonet dependency in the child eclipse manually works, correct?

**Comment by cubranic** [comment]
> I am assuming the work-around of adding the bayonet dependency in the child eclipse manually works, correct?

Yes, it does. I'm sure there is a way of having it automatically added, probably by some currently-missing bits of Eclipse integration, the way Xtext "nature" is already added. Or maybe with a "launcher" that would apply to .bl files and show up under "Run as...".

**Comment by alexandrebouchard** [comment]
Perfect, then I will close this issue for now and we can revisit it later on if other possibilities fail.
